FROM silkeh/clang:18 AS base

RUN apt-get update && apt-get install -y --no-install-recommends \
    valgrind \
    coreutils \
    && rm -rf /var/lib/apt/lists/*

RUN useradd --no-log-init -m -s /bin/false sandbox

RUN mkdir -p /work /out && chown sandbox:sandbox /out

WORKDIR /work
USER sandbox

ENTRYPOINT ["bash", "-c"]
